corrected_words = ['absence','accommodate',
'achieve','across','aggressive','apparently','appearance','argument','assassination',
'basically','beginning','believe','business','calendar','caribbean','category',
'cemetery','colleague','coming','committee','completely','conscious',
'copyright','curiosity','definitely','disappear','disappoint','ecstasy','embarrass','envioronment',
'existence','familiar','finally','fluorescent','foreign','forty','forward','friend','further',
'glamorous','government','grammar','gauge','happened','harass','harassment','honorary','humorous','immediately',
'incidentally','independent','interrupt','irresistible','knowledge','lighting','medicine','millennium','misspell','necessary',
'noticeable','occasion','occurred','occurrence','parallel','persistent','philippines','piece',
'politician','possession','preferred','preferring','privilege','pronunciation','publicly',
'really','receive','referred','religious','remember','resistance','sense',
'separate','successful','surprise','tendency','therefore','threshold','tomorrow',
'tongue','truly','unforeseen','unfortunately','until','vicious','weird','wherever',
'weather','whether','which']